### PR TITLE
Home .fwd file added

### PR DESCRIPTION
**Pull request by fabriciojs**
Solves https://github.com/fireworkweb/fwd/issues/63 - adding the possibility to load .fwd file from the current user home directory.

Also I am adding a new .fwd.install which is a version of the default .fwd file to be placed in the local project, but with only some variables active (not-commented) - the variables I consider the most important to be project-specific, and should not be updated without developer attention during a fwd upgrade for example.

### CODE REVIEW

**Comment by fabriciojs** [comment]
Also I am adding a new `.fwd.install` which is a version of the default `.fwd` file to be placed in the local project, but with only some variables active (not-commented) - the variables I consider the most important to be project-specific, and should not be updated without developer attention during a `fwd` upgrade for example.

**Comment by dbpolito** [comment]
I don't think we need `.fwd` and `.fwd.install`, i would update the current `.fwd` for that and just make sure all `env()` calls has the proper default value.

Or if we want that just for clarity let's get rid of all `env()` default values we have.

**Comment by fabriciojs** [comment]
I like the clarity of the .fwd file holding all of the values - so remove all the default values in-code.

Now having the second version commented out is bad for maintenance. Maybe the best then is:

1. Keep only one .fwd file with all default values. (For Backwards compatibility we can start having versions of it; that is for the future)

2. During install comment out everything and uncomment only what we suggest being versioned.

**Comment by dbpolito** [comment]
Sounds good

**Comment by fabriciojs** [comment]
@dbpolito PR updated.

**Pull request merged**
